### ISSUE TITLE
I bought the wrong chip

### ISSUE THREAD

**Issue by jordanadania** [jasoncoon/esp8266-fastled-audio#10]
I bought the stereo chip with 2 outputs.

For this code, which channel would result in the best visualizations? Left or Right?

Also, is there any code I can use to take advantage of the dual channel chip I bought?

Thanks!

**Comment by zombodotcom** [comment]
https://github.com/zombodotcom/ESP8266FastLedAudioMSGEQ7/blob/4aea4f55e2411ba9157e757e6a0baca3eabdbf34/Nodemcu_Amica_esp8266_WebserverAudio.ino

this has some left and right features. might take a little to read into, but it's something.

here's also another, 

https://github.com/zombodotcom/AuraRadiate2/blob/master/Auraradiate2.ino

aura radiate was created by another guy, Drew André
