### ISSUE TITLE
Wifi Manager

### ISSUE THREAD

**Issue by jordanadania** [jasoncoon/esp8266-fastled-audio#12]
Hello Mr. Coon,

I got lucky and went back to your original webserver to fix a bug in my code and I noticed you had updated the code and added a Wifi Manager.  This might be my favorite update to your code as it was the only thing holding me back from sharing your firmware with people who don't know how to program an arduino.  Anyway, I noticed that you did not also make these changes to the audio version -- my favorite version.

I am absolutely going to copy your wifimanager code over to my unique version of your firmware, but i was wondering if you wanted me to update your audio code since you are probably too busy.  I wanted to ask before I spent any time on it.  If you are cool with that, is the process for that:

1) fork my own copy 2) update it 3) pull request using that updated fork on your original project

would you ever consider adding me on discord if i promised to almost never bug you? [twice a year at most] :-)
If yes, [ Evo#8025 ]

do you have a donation link?

Thanks so much for your time!
Jordan Adania

**Comment by jasoncoon** [comment]
Jordan, 

That would be great, I would definitely welcome your pull request, thank you!

Sorry, I don't have a Discord account, and don't really plan on getting one.  I'm old school, and prefer asynchronous communication here, or [via email](https://www.evilgeniuslabs.org/contact), so I can reply when I'm available.  😆 

I don't really have a donation link, but I welcome coffee/beer money here: https://www.paypal.me/evilgeniuslabs

Thanks!
