### ISSUE TITLE
Android AP Mode not loading pages correctly

### ISSUE THREAD

**Issue by zombodotcom** [jasoncoon/esp8266-fastled-audio#3]
I set the esp8266 into AP mode and when i try and load into the page, its not giving the full webpage, and simple mode is only showing On and Off =( (Using chrome web browser in android)

**Comment by zombodotcom** [comment]
tried editing the index.htm and simple.htm
and uncommented 
` 
  <link rel="stylesheet" href="css/bootstrap.min.css">
  <link rel="stylesheet" href="css/jquery.minicolors.min.css">`

`
  <script src="js/jquery-3.1.1.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/jquery.minicolors.min.js"></script>
  <script src="js/r-websocket.min.js"></script>`
still no full page load from AP mode

**Comment by jasoncoon** [comment]
I haven't tried AP mode in a long while, but I don't see why that wouldn't work.  Questions:

1. Have you tried opening Chrome dev tools to the network tab, refreshed, and watched the requests & responses?
2. What ESP8266 board are you using?
3. Have you gzipped all of the files in data/?

**Comment by zombodotcom** [comment]
Turns out its not just AP mode with the edits to load the js files from the wemos d1 mini, it just doesnt load at all if trying to load from the edits even gziped edits. but gziping the files does fix the issue where it doesnt even load the rest of the page at all even after reflashing the wemos d1 mini

**Comment by zombodotcom** [comment]
![content mismatch](https://user-images.githubusercontent.com/13477955/27762402-b046f6b0-5e2e-11e7-9a04-c10af970ccd6.png)

**Comment by jasoncoon** [comment]
Need to see the Network tab.

I had problems with this early on in the dev of the web app, and ended up combining all of the js into one file, and all of the css into one file, to limit the number of requests the ESP8266 had to handle simultaneously.

**Comment by zombodotcom** [comment]
i gzipped all the files, but gunzipped the fonts like it said in the readme. 

![working](https://user-images.githubusercontent.com/13477955/27762632-462c74da-5e33-11e7-881d-68655e0be8a0.png)
Working gzip load (fonts not gzipped)


![non edited after first fail from editing](https://user-images.githubusercontent.com/13477955/27762635-53f1df4c-5e33-11e7-84f5-afd63c3f94b0.png)
here is the screenshot of the unzipped not loading with no edited data files from the non working after uploading the edited index to load the javascript files from the esp8266. 



load from esp8266 index gzipped
![loadjsfromesp8266 gzip](https://user-images.githubusercontent.com/13477955/27762641-71cdcbc0-5e33-11e7-9553-a2d307f10f1c.png)

**Comment by jasoncoon** [comment]
OK, yeah, it looks like the browser loads the HTML page, then simultaneously requests all of the resources (js, css, etc).  This isn't a problem for most web servers, but I don't think the ESP8266 can handle it, and it just drops some of them.

One solution is to combine all of the css files into one file, and all of the js files into one file.  I just pushed a commit that does this.  You'll just need to comment out the CDN and separate entries for css and js in the index html file, and uncomment the combined:  https://github.com/jasoncoon/esp8266-fastled-audio/commit/c1717158056199a24fc3a9d8a39bf42e2f47dcdd

**Comment by zombodotcom** [comment]
Combined with all other parts commented out like cdn and app.js and the 
```
 <!-- request js from the ESP8266 web server -->
  <!-- <script src="js/jquery-3.1.1.min.js"></script> -->
  <!-- <script src="js/bootstrap.min.js"></script> -->
  <!-- <script src="js/jquery.minicolors.min.js"></script> -->
  <!-- <script src="js/r-websocket.min.js"></script> -->

  <!-- request combined js from the ESP8266 web server -->
  <script src="js/combined.js"></script>

 <!--  <script src="js/app.js"></script> -->
```

```
  <!-- request CSS from internet CDN -->
 <!--  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-minicolors/2.2.4/jquery.minicolors.min.css" integrity="sha256-4wnSkPYU5B4yngAlx/rEb8LdfMah4teUth4AfhGEuaY=" crossorigin="anonymous" /> -->

  <!-- request CSS from the ESP8266 web server -->
  <!-- <link rel="stylesheet" href="css/bootstrap.min.css"> -->
  <!-- <link rel="stylesheet" href="css/jquery.minicolors.min.css"> -->

  <!-- request combined CSS from the ESP8266 web server -->
  <link rel="stylesheet" href="css/combined.css">

  <!-- <link rel="stylesheet" href="css/styles.css"> -->
```

ungzipped
![combined nongzip](https://user-images.githubusercontent.com/13477955/27763032-7b005be4-5e39-11e7-92c0-94671724fa4a.png)


gzipped combined

![gzippedcombined](https://user-images.githubusercontent.com/13477955/27763049-b4612184-5e39-11e7-951c-d7b58d478177.png)

**Comment by jasoncoon** [comment]
If you load the page again (enter in the address bar, not refresh) does it work?  Or at least fully load the next file?  Once the file is fully loaded, it'll be cached by the browser and won't be requested from the ESP8266 for at least 24 hours (controlled on line 457 by the max-age parameter).

Are you planning to use this somewhere without internet access?  Honestly, serving these large files might just be too much to ask of a ESP8266.

Not sure when I'll get my stuff unpacked, but when I do I'll try to reproduce this issue.

**Comment by zombodotcom** [comment]
I think I fixed it.  in  <ESP8266WebServer.h>

```
#define HTTP_DOWNLOAD_UNIT_SIZE 8192
#define HTTP_UPLOAD_BUFLEN 2048
```

to 

```
#define HTTP_DOWNLOAD_UNIT_SIZE 2048
#define HTTP_UPLOAD_BUFLEN 2048
```
![fixedlibrary](https://user-images.githubusercontent.com/13477955/27763442-04651102-5e41-11e7-8712-0b6844bfe4fe.png)

**Comment by jasoncoon** [comment]
Cool, good work!

Strange, though, I can't reproduce the issue here.  I'm using a Wemos D1 Mini Pro, I've tried at 80 MHz and 160 MHz.  Running this sketch, using the combined css and js, all files gzipped (including fonts).

![image](https://user-images.githubusercontent.com/3598755/27763658-fc661ff8-5e4c-11e7-9761-5c5f1d1042f1.png)

**Comment by zombodotcom** [comment]
maybe we have a different <ESP8266WebServer.h>

**Comment by jasoncoon** [comment]
I have the lates esp8266 core, version 2.3.0 installed with the Arduino board manager.  I haven't tried pulling the latest directly from github.

Here are all of the library versions shown in the compile output:

```
Using library FastLED at version 3.1.5 in folder: C:\Users\Jason\Documents\Arduino\libraries\FastLED 
Using library ESP8266WiFi at version 1.0 in folder: C:\Users\Jason\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi 
Using library ESP8266WebServer at version 1.0 in folder: C:\Users\Jason\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WebServer 
Using library ESP8266HTTPUpdateServer at version 1.0 in folder: C:\Users\Jason\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266HTTPUpdateServer 
Using library arduinoWebSockets at version 2.0.6 in folder: C:\Users\Jason\Documents\Arduino\libraries\arduinoWebSockets 
Using library EEPROM at version 1.0 in folder: C:\Users\Jason\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\EEPROM 
Using library Hash at version 1.0 in folder: C:\Users\Jason\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\Hash 
```

**Comment by jasoncoon** [comment]
Ah, yeah.

C:\Users\Jason\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WebServer\src\ESP8266WebServer.h

#define HTTP_DOWNLOAD_UNIT_SIZE 1460
#define HTTP_UPLOAD_BUFLEN 2048

**Comment by jasoncoon** [comment]
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WebServer/src/ESP8266WebServer.h#L35-L39

**Comment by zombodotcom** [comment]
Yeah I noticed mine was different , idk how it changed but I just deleted all of it and reinstalled all of the libraries. Sorry for the trouble!

**Comment by jasoncoon** [comment]
No worries, glad you got it worked out!  I hadn't messed with AP mode or hosting the CSS and JS locally in a while, so it was good to try it out again.
