### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by jordanadania** [jasoncoon/esp8266-fastled-audio#8]
I wanna be like coon. just tell me what to dooo. what is this thing called audio?

**Comment by jasoncoon** [comment]
I updated the readme with a bit more info.  :)  https://github.com/jasoncoon/esp8266-fastled-audio/blob/master/README.md

**Comment by jordanadania** [comment]
I cant wait. The web server project of yours changed my life. Im sure this one will be just as fun. Thank you!

**Comment by jordanadania** [comment]
How do I combine the two chips?

**Comment by jordanadania** [comment]
Okay so this is a microphone-driven, led-reactive-to-audio project?

Do you know of any good ways to make my leds react to my pcs audio while connected to it? I am currently using Prismatik's audio visualizer, but was wondering if there were other options.

Thank you!

**Comment by jordanadania** [comment]
I have touched this code every single day since this message. OMG <3
